/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAdvancedFlexTable: typeof import('./src/common/components/tables/VAdvancedFlexTable.vue')['default']
    VBtn: typeof import('./src/common/components/VBtn.vue')['default']
    VCardList: typeof import('./src/common/components/VCardList.vue')['default']
    VCarousel: typeof import('./src/common/components/VCarousel.vue')['default']
    VCart: typeof import('./src/common/components/VCart/index.vue')['default']
    VCartCounter: typeof import('./src/common/components/VCart/Counter.vue')['default']
    VCartItem: typeof import('./src/common/components/VCartItem.vue')['default']
    VCartList: typeof import('./src/common/components/VCartList/index.vue')['default']
    VCartListCartItem: typeof import('./src/common/components/VCartList/CartItem.vue')['default']
    VCartListCounter: typeof import('./src/common/components/VCartList/Counter.vue')['default']
    VCheckbox: typeof import('./src/common/components/VCheckbox.vue')['default']
    VConfirmationModal: typeof import('./src/common/components/modals/VConfirmationModal.vue')['default']
    VCopyInnerText: typeof import('./src/common/components/VCopyInnerText.vue')['default']
    VCursorLevel: typeof import('./src/common/components/VCursorLevel.vue')['default']
    VDatepicker: typeof import('./src/common/components/VDatepicker/index.vue')['default']
    VDatepickerOneDate: typeof import('./src/common/components/VDatepicker/OneDate.vue')['default']
    VError: typeof import('./src/common/components/VError.vue')['default']
    VErrorMessage: typeof import('./src/common/components/VErrorMessage.vue')['default']
    VExpandedPhoto: typeof import('./src/common/components/VExpandedPhoto.vue')['default']
    VExportBtn: typeof import('./src/common/components/VExportBtn.vue')['default']
    VFilterHeader: typeof import('./src/common/components/VFilterHeader.vue')['default']
    VFilterPanel: typeof import('./src/common/components/VFilterPanel/index.vue')['default']
    VFilterPanelDateItem: typeof import('./src/common/components/VFilterPanel/DateItem.vue')['default']
    VFixedHeaderNTable: typeof import('./src/common/components/tables/VFixedHeaderNTable.vue')['default']
    VFlexTable: typeof import('./src/common/components/tables/VFlexTable.vue')['default']
    VFlexTableCell: typeof import('./src/common/components/tables/VFlexTableCell.vue')['default']
    VFlexTableRow: typeof import('./src/common/components/tables/VFlexTableRow.vue')['default']
    VIcon: typeof import('./src/common/components/VIcon.vue')['default']
    VInput: typeof import('./src/common/components/VInput.vue')['default']
    VLoader: typeof import('./src/common/components/VLoader.vue')['default']
    VModalWrap: typeof import('./src/common/components/modals/VModalWrap.vue')['default']
    VMultiselect: typeof import('./src/common/components/VMultiselect.vue')['default']
    VNoData: typeof import('./src/common/components/VNoData.vue')['default']
    VPasswordField: typeof import('./src/common/components/VPasswordField.vue')['default']
    VProfileItem: typeof import('./src/common/components/VProfileItem.vue')['default']
    VProfileVProfile: typeof import('./src/common/components/VProfile/VProfile.vue')['default']
    VRadio: typeof import('./src/common/components/VRadio.vue')['default']
    VSearch: typeof import('./src/common/components/VSearch.vue')['default']
    VSearchFilter: typeof import('./src/common/components/VSearchFilter.vue')['default']
    VSearchFilterWithWorker: typeof import('./src/common/components/VSearchFilterWithWorker.vue')['default']
    VSideBar: typeof import('./src/common/components/VSideBar.vue')['default']
    VSidePanel: typeof import('./src/common/components/VSidePanel/index.vue')['default']
    VSidePanelInfoItem: typeof import('./src/common/components/VSidePanel/InfoItem.vue')['default']
    VSkeleton: typeof import('./src/common/components/VSkeleton/index.vue')['default']
    VSkeletonItem: typeof import('./src/common/components/VSkeleton/Item.vue')['default']
    VStatus: typeof import('./src/common/components/VStatus.vue')['default']
    VTableCell: typeof import('./src/common/components/VTableCell.vue')['default']
    VTabs: typeof import('./src/common/components/VTabs.vue')['default']
    VTooltip: typeof import('./src/common/components/VTooltip.vue')['default']
  }
}
